#!/bin/sh
#
# Robot framework linter script
#
# Copyright (C) 2018 Libre Space Foundation <https://libre.space/>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Create temporary directory
_dir="$(mktemp -d)"

# Copy current directory to temporary directory
cp -a . "$_dir"

# Tidy Robot files
python -m robot.tidy -r "$_dir"

# Compare original files with files generated by tidy
diff -qr . "$_dir"
_ret=$?

if [ $_ret -ne 0 ]; then
	# Report misformatting
	echo "Robot files are not formatted correctly!" >&2
fi

# Cleanup temporary directory
rm -r "$_dir"

# Exit with diff exit status
exit $_ret
